### ISSUE TITLE
How does one configure Slack to accept plugin calls?

### ISSUE THREAD

**Issue by metasim** [gitblit-org/gitblit-slack-plugin#1]
Not sure how to setup the Slack side of things. I'm trying to use the "Incoming WebHooks" feature in Slack, where it generates a webhook URL, but I can't find any place to generate a token. Any tips on the Slack side of things?

**Comment by gitblit** [comment]
Oy.  Slack has changed their advertised URLs.  You could try just using the
last hashed path segment of their advertised URL and see if that works.

**Comment by metasim** [comment]
Still trying to debug it, but I got further by defining `slack.hook` to point to the Webhook URL. From the best I can tell, this step is missing from the install docs. The test send message step now finishes silently, but I don't ever receive a message in Slack.

**Comment by metasim** [comment]
Yeh, no dice. When I run `ssh <hostname> slack test` I get a 404 from the Slack endpoint. Tried various formulations of `slack.token` and `slack.hook` without success.

**Comment by gitblit** [comment]
Yup.  My hook keeps chugging along, but that may be because my Slack
account is older.

The fundamental issue is this LOC:

 return String.format("https://%s.slack.com/services/hooks/%s?token=%s",
team.toLowerCase(), hook, token);
which apparently is invalid for newer Slack accounts.

**Comment by metasim** [comment]
How bad of an idea would it be to expose the format string as a config property?

PS: With your slack account, are you using it via the "Incoming WebHooks" feature?:

![screen shot 2015-02-04 at 1 43 06 pm](https://cloud.githubusercontent.com/assets/131013/6046868/c774b9f4-ac73-11e4-9934-c229e15dd10f.png)

**Comment by metasim** [comment]
PPS: My settings look something like this:

```
slack.team = foobar
slack.token = xoxp-2304675908-2304123785-3647258168-9268c2
slack.hook = T028YKVSQ/B02J2CNBD/bmjBGrbvKx37OBZRTR4e37oK
slack.defaultChannel = gitblit
```

**Comment by gitblit** [comment]
I hope you sanitized those... if not we'll delete.  Try removing the `slack.hook` setting and changing  `slack.token` to `bmjBGrbvKx37OBZRTR4e37oK`.  If team is correct, it might work.

**Comment by metasim** [comment]
Yeh, they were sanitized. Thanks for asking. 

w00t! It works!! I guess I didn't test it properly before.

Thanks so much for your help!

**Comment by metasim** [comment]
Followup Kudos: The information and formatting fed into Slack is absolutely fantastic. Very impressive integration on the end-user front! Dev team is very excited about it. Thanks for writing it.

**Comment by gitblit** [comment]
Your very welcome!​
