### ISSUE TITLE
Slack message garbled

### ISSUE THREAD

**Issue by petterl** [gitblit-org/gitblit-slack-plugin#2]
After installing the plugin and setting the config similar to bellow (not exact token and team)

```
slack.team = team
slack.token = b424ItUa313HtUcbbGEuyBY
slack.defaultChannel = sandbox
```

The messages sent to slack looks like:

```
psa has pushed 1 commit to </log?r=limego/go.git&h=feature/auto-signup-2|feature/auto-signup-2> in </summary?r=limego/go.git|limego/go>
</commit?r=limego/go.git&h=7bccb1fac9a4385d6db486cb700f0c9823eb9e64|`7bccb1`> Show information of signups in admin
```

What would be wrong for this to happen?

**Comment by gitblit** [comment]
Can you confirm that you have specified `web.canonicalUrl`?  This is the addressable base URL of your Gitblit install and is used for plugin link generation and email notifications.

**Comment by petterl** [comment]
True, that was not set making the links invalid. 
Thank you for quick reply.

PS. Documenting that the "token" is the last part of an webhook would be good since it was a hassle to figure out.

**Comment by gitblit** [comment]
It was correctly documented, but then Slack changed the presentation of the hook configuraiton which makes my current documentation look incorrect.  But I agree, the documentation needs to be updated to reflect Slack's current preferred configuration.  I presume you discovered #1.
