### ISSUE TITLE
Slack plugin is no longer working

### ISSUE THREAD

**Issue by urkle** [gitblit-org/gitblit-slack-plugin#3]
It stopped working after June 3rd.  And when I try to test via the ssh CLI it states "peer not authenticated".

How can I further diagnose what is going on here?   And should this plugin simply be reworked to use the full hook URL instead since that is what slack is now preferring?

**Comment by gitblit** [comment]
Yeah, redesigning for the full url is probably a good idea.

**Comment by gitblit** [comment]
Hmm.  My gitblit is posting to Slack just fine from all plugin entry points.

Could it be that your token has changed?

**Comment by urkle** [comment]
I checked that and the token was the same.  (the last part of the hook URL).

**Comment by pastephens** [comment]
Any progress on this issue? I see that the slack plugin is installed on my server, but events are not posting to slack.

**Comment by urkle** [comment]
it started working on my system about a week after reporting this (randomly).. though redesigning the plugin to use the recommended URL is best to ease the setup for new people and to handle any potential future breakage.
